### ISSUE TITLE
Ideas for improving the triangles tutorial sections 1.1 - 1.2

### ISSUE THREAD

**Issue by kennethshsu** [casact/chainladder-python#169]
Some ideas that I have for improving the first tutorial
- Can we include the installation here as step 1 (or 0)?
- Version of pandas and chainladder
- ```%matplotlib inline``` is used without introduction/explanation
- Some uncapitalized titles
- ```triangle.valuation_date``` seems weird (```Timestamp('1990-12-31 23:59:59.999999999')``` - separate issue ticket?)
- Probably a good idea to show what the raw data looks like in a normal dataframe and then convert to the triangle format
- Probably need to introduce the result of Y from ```trinalge.grain``` (stands for Year)

**Comment by jbogaardt** [comment]
Wonderful suggestions.

**Comment by kennethshsu** [comment]
On "triangle.valuation_date seems weird: Timestamp('1990-12-31 23:59:59.999999999'), is this intended? Or can we (or I try to) fix this?

**Comment by jbogaardt** [comment]
What specifically do you think is weird?  Do you mean the '23:59:59.999999999' portion is weird or the date itself?  The idea of the "valuation_date" is to have a datetime that is at the terminal timestamp of the period, i.e. the last split second of the the year.

We could use date only instead of having the baggage of the timestamp, but In pandas, dates seem to have more restrictions when used in boolean expressions.  For example:
```python
import pandas as pd
date_time = pd.Timestamp('1990-12-31 23:59:59.999999999')
pd.Series(date_time) < '1991'  # This is a valid boolean expression 

date_only = pd.Timestamp('1990-12-31').date()
pd.Series(date_only) < '1991' # This fails
```
Because of this, we use Timestamps for both the `valuation_date` and the `valuation` vector.

**Comment by kennethshsu** [comment]
This makes sense, thanks!

Will try to revise the other points in the tutorail.
