### ISSUE TITLE
`incr_to_cum()` then `cum_to_incr()` does not result in the original triangle?

### ISSUE THREAD

**Issue by kennethshsu** [casact/chainladder-python#174]
```Python
import pandas as pd
import numpy as np
import chainladder as cl
prism_df = pd.read_csv(
    "https://raw.githubusercontent.com/casact/chainladder-python/master/chainladder/utils/data/prism.csv"
)
prism = cl.Triangle(
    data=prism_df,
    origin="AccidentDate",
    origin_format="%Y-%m-%d",
    development="PaymentDate",
    development_format="%Y-%m-%d",
    columns=["Paid", "Incurred"],
)
prism_cum = prism.incr_to_cum()
prism_incr = prism_cum.cum_to_incr()
prism == prism_incr
```

This block of code will return false on the last comparison.

**Comment by jbogaardt** [comment]
This is a classic floating point precision problem.  Checking the maximum difference shows we have a near-zero, but non-zero difference 
```python
>>> (abs(prism - prism_incr)).max().max().max()
1.4115357771515846e-09
```
We could perhaps modify the `__eq__` method to have a some tolerance for non-zero values, or just leave it as False since they technically are not equal.  Unfortunately, the floating point precision problem is a general computng problem and not specific to `chainladder`.  Not sure what we should do here.  What do you recommend?

More info:
https://docs.python.org/3/tutorial/floatingpoint.html

**Comment by kennethshsu** [comment]
Hmm.. I was going to propose that we always round all figures in the triangle to a certain decimal precision, but than I realized that we could always have triangle metrics that are percentage based, such as % closed, or losses per mile, that could result in figures being tiny. Maybe it's best to just leave it alone.
