### ISSUE TITLE
heatmap() should take an additional argument that can null the bottom half of the triangle

### ISSUE THREAD

**Issue by kennethshsu** [casact/chainladder-python#196]
A use case would be when calculating actual vs expected (expected is a squared triangle), taking the difference of the two can sometimes yield numbers close to 0, but nonzero values at the lower bottom half of the triangle.

**Comment by kennethshsu** [comment]
Thinking about this more, I think we just need a method that will null the bottom half of the triangle. What are your thoughts on `.emptyprojection()`? Is there a better name?

**Comment by jbogaardt** [comment]
I like your first suggestion better for two reasons.

1. Creating new methods should be done very judiciously.  I believe conforming to existing methods and functionality of pandas/numpy/sklearn is the key reason chainladder-python has as many users as it does. It makes it easier to learn.  There are chainladder-specific methods for sure, but they are usually reserved for commonly used but complex actuarial-specific data transformations.  Censoring the bottom half of a triangle is a trivial one-liner: `tri[tri.valuation<some_date]`. Its hard to buy into needing a whole new method for something so trivial. 
2. It's not clear to me how `emptyprojection` would know the appropriate valuation dates to censor. This issue typically arises on triangles with valuation dates at ultimate that need to be censored to the valuation date of the original triangle. Not sure how to get that exogenous information into the method without asking for it.  It can't be inferred from the last origin period because the notion of "bottom half" for asymmetric triangles (e.g. OYDM) is ambiguous without knowledge of a valaution_date.

Your first suggestion, something like `tri.link_ratio.heatmap(atol=1e-6)` ,has a lower footprint on API complexity.  It does the job and it reinforces numpy naming convention.

**Comment by kennethshsu** [comment]
Cool, will leave it as is. 

Agree that it is easy to just get the upper half of the triangle with the one-liner.
