### ISSUE TITLE
Error : 'M' <class 'KeyError'>

### ISSUE THREAD

**Issue by Dayananda02** [casact/chainladder-python#223]
During the triangle creation for granulity **Year** , i am getting error as 'M' key error.
Could not find much information about what exactly error.
Error at exception : 
keyerror('M')

**Comment by jbogaardt** [comment]
The library has a contraint that `development_grain`s that are no less granular than `origin_grain`. Here, the data itself enforces that, but the `development_grain` property is being set incorrectly to 'Y' and not 'M'. It needs to be 'M'  because of this constraint.

Here's a working example of your data using `chainladder==0.8.9`:

```python
df = pd.read_clipboard()

tri = cl.Triangle(
    data=df, columns='CLMOSGROSS',
    origin='POLFMDT', development='OSDT', cumulative=False)

tri.development_grain = 'M' # Shouldn't have to do this, this is the bug

tri.grain('OYDY').incr_to_cum()
```

**Comment by dayananda0202** [comment]
Its working .. Thank you 👍
