### ISSUE TITLE
Functionality to fillna

### ISSUE THREAD

**Issue by kennethshsu** [casact/chainladder-python#260]
Be able to fillna on a triangle, such as taking in a vector and fill across origins

**Comment by kennethshsu** [comment]
I'm working on this...

**Comment by kennethshsu** [comment]
Here's my proposed docstring:
```
Fill nan with 'value' by axis.
Parameters
-----------
value: single value or array-like values, default = None
    Value(s) to fill across the axis.

axis: {3 or ‘origin’, 4 or ‘development’}, default = 3
    Whether to fill the value(s) along rows (3 or ‘origin’)
    or columns (4 or ‘development’).
    
inplace: boolean, default = False
    Whether to modify the triangle object directly (True), or
    return a new modified triangle (False).

triangle: boolean, default = True
    Whether to preserve the filled object as a triangle (True),
    or to square the triangle with the value(s) (False).

Returns
-------
Triangle
```

I tested the following code, they all work
```python
import pandas as pd
import chainladder as cl

cl.__version__
%load_ext lab_black

raa = cl.load_sample("raa")
latest_raa = raa[raa.valuation > "1990-01-01"]

latest_raa.fillna([100, 200, 300, 400, 500])
latest_raa.fillna([100, 200, 300, 400, 500], triangle=False)
latest_raa == latest_raa.fillna(
    [100, 200, 300, 400, 500], triangle=False, inplace=False
)
latest_raa == latest_raa.fillna([100, 200, 300, 400, 500], triangle=False, inplace=True)

latest_raa = raa[raa.valuation > "1990-01-01"]
latest_raa.fillna([100, 200, 300, 400, 500], triangle=True, inplace=False, axis=3)
latest_raa.fillna(
    [100, 200, 300, 400, 500], triangle=True, inplace=False, axis="origin"
)
latest_raa.fillna(
    [100, 200, 300, 400, 500], triangle=True, inplace=False, axis="development"
)
latest_raa.fillna(
    [100, 200, 300, 400, 500], triangle=False, inplace=False, axis=4
)
latest_raa.fillna(50, triangle=True, inplace=False, axis="origin")
latest_raa.fillna(50, triangle=True, inplace=False, axis="origin") == latest_raa.fillna(
    50, triangle=True, inplace=False, axis="development"
)
```

**Comment by kennethshsu** [comment]
Now, back to my goal of filling in the triangle with a diagonal, the code needed is super lengthy. Any ideas on how to simplify this?
```python
latest_raa.fillna(
    latest_raa.latest_diagonal.to_frame().to_numpy().flatten(order="C").tolist()
)
```

**Comment by jbogaardt** [comment]
Not sure this helps with`fillna`, but triangle arithmetic can be used to fill inner diagonals:

```python
import chainladder as cl
raa = cl.load_sample("raa")
raa * 0 + raa.latest_diagonal
```
With your implementation, you can make a expression for the fill vector smaller by recognizing this equality:
```python
(
    latest_raa.latest_diagonal.to_frame().to_numpy().flatten(order="C").tolist()  == 
    list(latest_raa.sum(3).values.squeeze())
)
```
It would be nice if fillna supported a `Triangle` as a fill value rather than converting things to arrays and lists.

**Comment by kennethshsu** [comment]
```python
raa * 0 + raa.latest_diagonal
```
This is super useful! I didn't know this trick!

Where is this? Maybe we can discuss this next time.

**Comment by kennethshsu** [comment]
```python
raa * 0 + raa.latest_diagonal
```
This is super useful! I didn't know this trick!

Where is the code that does the arithmetic? Maybe we can discuss this next time.

**Comment by kennethshsu** [comment]
> It would be nice if fillna supported a `Triangle` as a fill value rather than converting things to arrays and lists.

On this note, I supposed we just need to check if the `Triangle` object only has data in one of the axis? Then use that axis as the array? Is that what you are thinking about?

**Comment by jbogaardt** [comment]
Its not well documented, but the rules of arithmetic between two triangles are as follows:

If any axes on one of the triangles is a length of 1, then that axis will broadcast like a numpy array. 
```python
# chainladder arithmetic
raa * 0 + raa.latest_diagonal
# behaves like numpy arithmetic
(raa * 0).values + raa.latest_diagonal.values
```
If two axes are both of length 1 AND they have different labels, then the result will inherit the label from the left hand triangle. There is no numpy equivalent since numpy does not maintain labels:
```python
# Has a valuation of 2261
cl.Chainladder().fit(raa).ultimate_  -  raa.latest_diagonal 
# Has a valuation of 1990
-raa.latest_diagonal + cl.Chainladder().fit(raa).ultimate_ 
```
After broadacsting rules, the axis labels will be matched (like a merge key) when there are consistent axis labels. This is consistent with pd.DataFrame arithmetic:
```python
# chainladder arithmetic
raa[(raa.development>=24)&(raa.development<=60)] / raa
# behaves like pandas DataFrame arithmetic
raa[(raa.development>=24)&(raa.development<=60)].to_frame() / raa.to_frame()
```
However, in `chainladder` we've added additional rules for where axes don't match. Pandas only performs arithmetic on shared (intersection) of axis labels. `chainladder` performs arithmetic on the union of axis labels:
```python
# chainladder arithmetic - no common labels returns union
raa[raa.development<=48] + raa[raa.development>48]
# pandas arithmetic - no common labels returns full NaNs
raa[raa.development<=48].to_frame() + raa[raa.development>48].to_frame()
```
You can do further tricks by performing arithmetic on a `Triangle` and a numpy array. For example, you may not want label matching like a dataframe. You can bypass it by swapping in array values.
```python
# This is two triangles and labels will be matched
raa.iloc[..., 1:] / raa.iloc[..., :-1]
# Bypassing label matching to make homegrown link ratios. Notice the denominator is an array
raa.iloc[..., 1:] / raa.iloc[..., :-1].values
```

**Comment by jbogaardt** [comment]
Actually, we do loosely describe these rules in the [User Guide](https://chainladder-python.readthedocs.io/en/latest/triangle.html#arithmetic).

It's probably worth expanding on though because understanding triangle arithmetic eliminates the need for a lot of custom functionality. For folks like me that use really large sparse triangles, I know the arithmetic expressions will scale up.


Consider this implementation of `fillna`. Its more compact, fully vectorized, supports filling along all axes simultaneously. Fill value support Triangles and works for various array backends, all courtesy of a little arithmetic magic:
```python
def fillna(self, value):
    left = (self + value*0)
    xp = self.get_array_module()
    right = (xp.nan_to_num(left.values)==0)*(self*0 + value)
    return left + right
```

**Comment by kennethshsu** [comment]
Wow this is great, thanks for writing that up. 

And your code is so clean! I also just realized my code doesn't really fill the NAs, it fills everything. Will revise soon...

**Comment by kennethshsu** [comment]
I'm trying to follow your code to get `inplace` to work, can you point out what I am missing?
```python
def fillna(self, value=None, inplace=False):
    obj = self if inplace else self.copy()
    
    frame = (obj + value*0)
    xp = obj.get_array_module()
    fill = (xp.nan_to_num(frame.values)==0)*(obj*0 + value)
    obj = frame + fill
    
    return obj
```
Test code:
```python
import pandas as pd
import chainladder as cl
quarterly = cl.load_sample("quarterly")
quarterly_latest = quarterly[quarterly.valuation >= "2006"].grain("OYDY")
quarterly_latest["incurred"].fillna(
    quarterly_latest["paid"].latest_diagonal, inplace=True
)
quarterly_latest["incurred"]
```

**Comment by jbogaardt** [comment]
To mutate self you have to return self:
```python
def some_method(self, inplace=False):
     if inplace:
         # Do something directly to self
         return self
     else:
         new_obj = self.copy()
         return new_obj.some_method(inplace=True)
```
I'm not convinced that all the `inplace` arguments in chainladder work correctly, but the above pattern does.

**Comment by kennethshsu** [comment]
Yes I think I understand what you are saying by the function above. What do you mean by 
> I'm not convinced that all the inplace arguments in chainladder work correctly, but the above pattern does.

**Comment by jbogaardt** [comment]
I just mean that if you followed the code base for your first attempt and it didnt work, then the part you followed likely doesn;t work either.
