### ISSUE TITLE
Function to check if .ldf_ .cdf_ is monotonic

### ISSUE THREAD

**Issue by kennethshsu** [casact/chainladder-python#279]
Is it possible to quickly check if LDFs or CDFs are monotonic? If not, it would be useful to check which age-to-age factor(s) are in violation.

For this, is it better to implement it as a function? Or should we just throw a warning? I think a warning could be a bit annoying, especially for segments that downward development is expected (such as salvage and subrogation).

**Comment by jbogaardt** [comment]
Checking monotonicity using pandas:
```python
import chainladder as cl
assert cl.Development().fit(cl.load_sample('abc')).ldf_.to_frame().iloc[0].is_monotonic_decreasing
```
This is a good one that highlights for me an unwritten philosophy with which I approach the chainladder-python library. I view it as complementary to pandas and numpy, not a replacement for them. If we can use those packages without breaking a reserving workflow, my preference is to use them.  Checking monotonicity is a good example of that. My inclination is to say we don't need a function because pandas has one.  Pandas will have a better implementation with better documentation, and each line of code we avoid maintaining is technical debt avoided.

**Comment by kennethshsu** [comment]
That's a very good point, I'll try to follow that going forward.

**Comment by jbogaardt** [comment]
Should this be reclassified as a discussion forum Q&A?

**Comment by kennethshsu** [comment]
Yes I think so.
