### ISSUE TITLE
Changing the default date format of the year in 'valuation_date’ which corresponds to latest diagonal generated from development triangles.

### ISSUE THREAD

**Issue by SRwcf** [casact/chainladder-python#451]
**Is your feature request related to a problem? Please describe.**

**Is your feature request at odds with the scope of the package?**
The ethos governing `chainladder-python` is that it:
1. Is an engine for triangle manipulation and reserve setting. It is not a reserving system, but can be a major component in a reserving system, such as [FASLR](https://faslr.com/).
2. Conforms to `pandas` and `sklearn` API in a strict sense. Deviations from these APIs is discouraged. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SRwcf** [comment]
Hi, while generating latest diagonal from development triangles. It corresponds to a 'valuation_date’ which I believe is a datetime that is at the last split second of the year. Would it be possible to change the default last date format of the year i.e., from 20XX-12-31 to 20X-07-16 so that we could see the loss evaluation as on mid-July? I am trying to develop triangles using Nepalese Calendar Year which runs from mid-July. Thanks for taking your valuable time to consider this request. I look forward to being guided by you. Regards, Som

**Comment by jbogaardt** [comment]
Good to hear from you @SRwcf.  The package currently doesn't support mid-month valuations. However, you should be able to assume any month end other than December for your triangles.

For example, you could have a fiscal year end in July by using the `trailing` option of the `grain` method.

```python
>>> import chainladder as cl
>>> prism = cl.load_sample('prism')['Paid'].sum()
>>> # Assume data is through the end of July. Trailing=True will make the origin axis cut-off at July.
>>> prism = prism[prism.valuation < '2017-08'].grain('OYDQ', trailing=True)
>>> # Verify cut-off is July: dtype=period['A-JUL']
>>> prism.origin
PeriodIndex(['2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
             '2016', '2017'],
            dtype='period[A-JUL]', name='origin')
```
This gives and Accident Year/Development Quarter triangle with fiscal cut-off of month end July.  I haven't played too much with these non-standard cut-offs since my company follows the calendar year. Let me know if you run into any rough edges with them.

**Comment by SRwcf** [comment]
Thank you so much @jbogaardt . You are awesome. I will do as you said. chainladder package is extremely useful especially during the financial close :)
