### ISSUE TITLE
SyntaxError: invalid syntax (core.py, line 178) when trying to import chainladder package

### ISSUE THREAD

**Issue by aegerton** [casact/chainladder-python#70]
I have created a reprex Project (https://rstudio.cloud/spaces/54476/project/1055533) in RStudioCloud with a virtual environment for Python3. When I try to load the chainladder package previously installed within that environment, it receives the following error message in RStudioCloud;-

```
> reticulate::repl_python()
Python 3.5.2 (/cloud/project/NSS/bin/python)
Reticulate 1.14.9001 REPL -- A Python interpreter in R.
>>> import chainladder as cl
SyntaxError: invalid syntax (core.py, line 178)
```

Here is the R script;-
```{r}
install.packages("devtools")
devtools::install_github("rstudio/reticulate")
library(reticulate)
virtualenv_create("NSS", python = "/usr/bin/python3")
virtualenv_install('NSS', 'chainladder')
use_virtualenv('NSS', required = T)
```

Here is the Python script;-
```{python}
import chainladder as cl
```
This works satisfactorily on my desktop version of R/RStudio.  Any suggestions, please?

**Comment by aegerton** [comment]
Other packages (e.g. pandas) do not have the same error message.

**Comment by jbogaardt** [comment]
@aegerton, You're playing in a would I am unfamilar with.  `chainladder-python` does not even have a `core.py` file so I am not even sure it is chainladder (vs one of its dependencies) throwing the exception.

I am noticing is that reticulate is spinning up python 3.5.2.  This is a very old distribution.  Is it possible to upgrade it to python>=3.6?  Technically chainladder syntax should be supported by python 3.5, but again I can't say the same for all the packages on which `chainladder` depends.  I just tried adding python 3.5 to my CI/CD pipeline and it fails to install all the dependencies without forcing downgrades.  Interesting you say `pandas` works because my pipeline fails because `pandas==1.0.0` is not supported on python 3.5.

That would be my first recommendation.

**Comment by jbogaardt** [comment]
Actually, I found the offending library `xlcompose` has `core.py`, and line 178 uses an f-string which is not supported on python 3.5.  I wrote `xlcompose` too, so I can make that one compatible.  Issue recreated [there](https://github.com/jbogaardt/xlcompose/issues/5).

I still recommend upgrading to python 3.6 though.  Closing this one out since it is not a `chainladder` issue.  Feel free to watch to `xlcompose` ticket.

**Comment by jbogaardt** [comment]
@aegerton, I released `xlcompose==0.1.9` to [pypi](https://pypi.org/project/xlcompose/) and it should be python 3.5 compatible now.  If you can blow away your environment and reinstall chainladder it should pick up the latest release.

**Comment by aegerton** [comment]
Thanks very much indeed @jbogaardt Really helpful and much appreciated!

The issue was resolved (although another has arisen).  

I have commented at the ```xlcompose``` library instead this time.

**Comment by aegerton** [comment]
@jbogaardt I came across another f-string in line 1436 of the Stochastic Methods tutorial (code block 23);-
```
    "print(f\"99%-ile of reserve estimate is {'{:0,}'.format(round(ibnr_99,0))}\")"
```
Sorry to be a pain!

**Comment by jbogaardt** [comment]
No worries, I do claim python 3.5 compatibility so I should keep the tutorials that way too.

**Comment by aegerton** [comment]
Thanks very much again @jbogaardt
