### ISSUE TITLE
Breaking packages with Mack

### ISSUE THREAD

**Issue by johalnes** [casact/chainladder-python#91]
Hi,
Have been trying the Mack model with different environments lately. Have made some runs with code from the different tutorials (which is great btw!)

Get different errors and different sizes on matrices depending on which packages is installed. 

__Test code:__

```
import numpy as np
import pandas as pd

import chainladder as cl

print(f'CL: {cl.__version__} \n PD:{pd.__version__} \n NP: {np.__version__}')

data = pd.read_csv('https://raw.githubusercontent.com/casact/chainladder-python/master/chainladder/utils/data/prism.csv')
data['AccYr'] = data['AccidentDate'].str[:4]

x = cl.Triangle(data=data,
            origin='AccYr', development='PaymentDate',
            columns=['Paid', 'Incurred'],
            origin_format='%Y', development_format='%Y-%m-%d').incr_to_cum()
print(x)
mack = cl.MackChainladder()
dev = cl.Development(average='volume')
mack.fit(dev.fit_transform(x))
print(mack.summary_['Paid'])

```
__Works with Nump 1.18.1, Pandas 1.0.3 and CL 0.7.1:__
CL: 0.7.1
 PD:1.0.3
 NP: 1.18.1
Valuation: 2017-12
Grain:     OYDM
Shape:     (1, 2, 10, 120)
Index:      ['Total']
Columns:    ['Paid', 'Incurred']
            Latest          IBNR      Ultimate  Mack Std Err
2008  1.512842e+08           NaN  1.512842e+08           NaN
2009  1.577487e+08  7.299454e+03  1.577560e+08  2.213477e+03
2010  1.618702e+08  1.679419e+04  1.618870e+08  8.865543e+03
2011  1.624907e+08  3.533297e+04  1.625260e+08  2.038287e+04
2012  1.528195e+08  9.627098e+04  1.529157e+08  3.625529e+04
2013  1.616730e+08  2.820432e+05  1.619551e+08  6.348720e+04
2014  1.549699e+08  8.741548e+05  1.558441e+08  1.926595e+05
2015  8.091458e+07  8.145133e+07  1.623659e+08  6.230596e+06
2016  1.858806e+07  1.950094e+08  2.135974e+08  2.298369e+07
2017  6.396536e+06  2.178719e+08  2.242684e+08  2.582959e+07

__Error when upgrading pandas:__
CL: 0.7.1
 PD:1.1.1
 NP: 1.18.1

  File "C:\Users\jalnes\.julia\conda\3\envs\chainladder_env\lib\site-packages\chainladder\methods\chainladder.py", line 95, in _get_ultimate_
    obj.values = (cdf*obj_tri)*nans
ValueError: operands could not be broadcast together with shapes (1,2,10,120) (1,2,5,120)

__Error when upgrading chainladder:__
CL: 0.7.5
 PD:1.1.1
 NP: 1.18.1

 File "C:\Users\jalnes\.julia\conda\3\envs\chainladder_env\lib\site-packages\chainladder\methods\mack.py", line 157, in _get_tot_param_risk
    t1 = xp.nan_to_num(self._full_triangle_.values)[..., :len(self.X_.ddims)] - \
ValueError: operands could not be broadcast together with shapes (1,2,10,120) (1,2,10,10)

Will try to look into it and try to contribute if I find anythin. But will probably take a while to just understand all methods.

**Comment by jbogaardt** [comment]
Thank you for reporting this @johalnes.  I really appreciate the reproducibility here.  If you can't find anything, no worries, I am able to reproduce your issue, so I'll take a look after work today.

**Comment by johalnes** [comment]
@jbogaardt sound good. Great work! Will try also because I would love to contribute in the future :) 

Note, I tried multiple versions and this occured for all versions after 7.1.

**Comment by jbogaardt** [comment]
Thank you @johalnes, it would be great to have additional contributors.  The package could be so much better with different perspectives.  As for this issue, I appear to have broken `MackChainladder` for any asymmertric triangles.  `MackChainladder` as written relies on the latest diagonal of the Triangle with the requirement that all development periods are retained.  My mistake was thinking that `tri[tri.valuation==tri.valuation_date]` does this.  In fact, it only works for symmetric triangles.  A more generalized approach is `tri - tri[tri.valuation<tri.valuation_date]`  that works for both symmertric and asymmetric triangles.

I've gone ahead and added an asymmetric triangle unit test so that it doesn't break silently again.  I didn't test all the different pandas versions, but clearly there was a bug in chainladder itself that needed to be cleared.  Mind letting me know if this clears the issue in all your environments?  Assuming all is well, I can push it into a 0.7.6 release with some other fixes and enhancements.

**Comment by johalnes** [comment]
I have ran different models with different combination of numpy, pandas and numba, and they all run perfectly. 
Exceptional work!
