### ISSUE TITLE
Enhance Grain adding Semester 

### ISSUE THREAD

**Issue by AugustoCL** [casact/chainladder-python#99]
Would be a good enhancement add the semester into the grain.

**Comment by jbogaardt** [comment]
This functionality is currently not supported in pandas. See pandas-dev/pandas#22362.  There is no easy workaround using `freq='2Q'` due to this bug in pandas: pandas-dev/pandas#15063.  Because of these issues, I think this one may take a while to resolve.

**Comment by telferm57** [comment]
I think another use case for this (and possibly more widely needed?) is selecting half year. Many reports require division in to half year (I am working on a few atm) - the functionality could be modelled on quarter , defining the month start for the half year (which would probably coincide with financial year ends, product launches, drug authorizations etc.). As previously noted, we cannot use a frequency of 2Q , because if there happens to be no data in January, but some in Feb it will start the 2 quarter period in February. It seems to be quite a big bit of functionality to be missing given the richness of the time period specification as a whole.

**Comment by kennethshsu** [comment]
Confirmed that `OSDS` works.

Does it make more sense to use `H` instead of `S` for half year? I think it also makes sense to have the origin text as YYYYH1 and YYYYH2 instead of YYYYQ1 and YYYYQ3 when in `OS`. Thoughts?

**Comment by jbogaardt** [comment]
Maybe support both H and S so as to avoid a deprecation.  Both are suboptimal since S is reserved for seconds and H for hours in the datetime module. As labeling goes, your suggestion is a good one.

**Comment by telferm57** [comment]
Could use 'h' for half year ? That is not used in strftime or groupby frequencies

**Comment by kennethshsu** [comment]
I agree that H more visually pleasing. A new version is coming!

If `origin_grain` is "S" or "H" (we'll support both), the table will show YYYYH1 YYYYH2, etc.

Sorry I don't have example code here to show, since there's no sample data that is at the monthly or quarterly level origin grain.

**Comment by jbogaardt** [comment]
The prism dataset is monthly

**Comment by kennethshsu** [comment]
Oh yes! Thanks!

```python
import pandas as pd
import chainladder as cl

prism = cl.load_sample("prism")
prism["Incurred"].sum().grain("OHDM")
prism["Incurred"].sum().grain("OSDM")
```

These should all work. I also tested some weird mutation and didn't get anything unexpected back.
